#!/bin/bash -eu
set -o pipefail

DOCKER_IMAGE=mkdo-build

if [[ $DOCKER_IMAGE != ${DOCKER_CONTAINER-} ]]; then
    if [[ $(uname -s) = Darwin ]]; then
        if [[ $(docker-machine status) = Stopped ]]; then
            docker-machine start
        fi
        eval $(docker-machine env)
    fi

    # FIXME: May behave strangely on symlinks
    source_dir="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")"

    docker build \
           --force-rm --rm=true \
           -t "$DOCKER_IMAGE" \
           "$source_dir/do/build-docker"

    output_dir="${source_dir}/build"
    if [[ -e "$output_dir" ]]; then
        echo rm -rf "$output_dir"
        rm -rf "$output_dir"
    fi
    mkdir "$output_dir"

    docker run \
           --env DOCKER_CONTAINER=$DOCKER_IMAGE \
           --read-only \
           --rm \
           --sig-proxy=true \
           --user $(id -u):$(id -g) \
           --volume="$source_dir:$source_dir:ro" \
           --volume="$output_dir:$output_dir:rw" \
           --workdir="$source_dir" \
           $DOCKER_IMAGE \
           "$source_dir/do/build"
    exit $?

fi

id
pwd
ls -al
